[general]
working_directory = "C:/Users/ahmadinne"
import = ["colors.toml"]
live_config_reload = true

[terminal]
shell = "pwsh"

[keyboard]
bindings = [
  { key = "Escape", chars = "~", mods = "Shift" },
  { key = "Space", action = "ToggleViMode", mode = "~Search", mods = "Control" },
  { key = "Q", action = "ToggleViMode", mode = "Vi" },
  { key = "Escape", action = "ToggleViMode", mode = "Vi" },
  { key = "Y", action = "Copy", mode = "Vi|~Search", mods = "Shift" },
  { key = "Insert", action = "Paste", mods = "Shift" },
  { key = "H", action = "High", mode = "Vi|~Search", mods = "Shift" },
  { key = "M", action = "Middle", mode = "Vi|~Search", mods = "Shift" },
  { key = "L", action = "Low", mode = "Vi|~Search", mods = "Shift" },
]

[env]
TERM = "xterm-256color"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "1", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|https://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^<>`]+"

[[hints.enabled]]
regex = '[^ ]+(?:\s*)$'
command = { program = "/usr/bin/tmux", args = ["split-window", "-h", "-c", "#{pane_current_path}", "sh", "-c", "nvim \"$0\""] }
binding = { key = "2", mods = "Control" }

[colors]
draw_bold_text_with_bright_colors = true

[window.dimensions]
columns = 70
lines = 17

[window.padding]
x = 10
y = 10

[font]
size = 13

[font.bold]
style = "bold"

[font.italic]
style = "italic"

[font.normal]
family = "Iosevka Nerd Font"
# family = "Inconsolata Nerd Font"
# family = "Hack Nerd Font"
# family = "RobotoMono Nerd Font"


[font.offset]
y = 0

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"
blinking = "On"

[[hints.enabled]]
command = "firefox"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[scrolling]
history = 500
