# Ahmadinne's Yasb Bar
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: true
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [ "microphone", "volume", "brightness" ]
      center: [ "glazewm_workspaces" ]
      right: [ "wifi", "battery", "clock" ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>󰅐</span> {%H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
      calendar: 
        blur: false
        round_corners: false
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "\u23fc Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      animation: false
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 20
        hide_label: true
        hide_duplicates: true
        hide_floating: false
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      tooltip: false
      volume_icons:
        - "󰖁"
        - "󰕿"
        - "󰖀"
        - "󰖀"
        - "󰕾"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      brightness_icons: [
        "󰽥",
        "󰽣",
        "󰽦",
        "󰽢"
      ]
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      icons:
        normal: "󰍬"
        muted: "󰍭"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_name}"
      get_exact_wifi_strength: false
      wifi_icons: [
        "󰤯",
        "󰤟",
        "󰤢",
        "󰤨",
        "\udb82\udd28"
      ]
  battery:
    type: "yasb.battery.BatteryWidget"
    options: 
      label: "<span>{icon}</span> {percent}%"
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: False
      status_thresholds:
        critical: 10
        low: 20
        medium: 40
        high: 70
        full: 100
      status_icons:
        icon_charging: "󱐋"
        icon_critical: "󰁺"
        icon_low: "󰁻"
        icon_medium: "󰁽"
        icon_high: "󰂀"
        icon_full: "󰁹"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\ue257"
      label_expanded: "\ue257"
      label_position: "left"
      icon_size: 10
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
