# Ahmadinne's Yasb Bar
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
show_systray: true # Show YASB on the system tray.
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    animation:
      enabled: false
    blur_effect:
      enabled: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    layouts:
      left:
        alignment: "left"
        stretch: true
      center:
        alignment: "center"
        stretch: true
      right:
        alignment: "right"
        stretch: true
    widgets:
      left: [ "wifi", "volume" ]
      center: [ "glazewm_workspaces" ]
      right: [ "clock" ]
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "\u23fc Glazewm Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      animation: false
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 20
        hide_label: true
        hide_duplicates: true
        hide_floating: false
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_name}"
      callbacks: 
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
      wifi_icons: [
        "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\wifi-off.svg' />",  # Icon for 0% strength
        "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\wifi-low.svg' />",  # Icon for 1-24% strength
        "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\wifi-low.svg' />",  # Icon for 25-49% strength
        "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\wifi-high.svg' />",  # Icon for 50-74% strength
        "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\wifi.svg' />"   # Icon for 75-100% strength
      ]
      menu_config:
        blur: false
        round_corners: false
        alignment: "left"
        direction: "bottom"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: [
          "\ue670",
          "\ue671",
          "\ue672",
          "\ue673",
        ]
        wifi_icons_unsecured: [
          "\uec3c",
          "\uec3d",
          "\uec3e",
          "\uec3f",
        ]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      volume_icons:
        - "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\volume-x.svg' />"  # Icon for muted
        - "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\volume-1.svg' />"  # Icon for 0-10% volume
        - "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\volume-1.svg' />"  # Icon for 11-30% volume
        - "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\volume-1.svg' />"  # Icon for 31-60% volume
        - "<img src='$env:USERPROFILE\\.config\\yasb\\svg\\volume-2.svg' />"  # Icon for 61-100% volume
      audio_menu:
        blur: false
        round_corners: false
        alignment: "left"
        direction: "bottom"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M - %a, %b %d}"

