# Ahmadinne's Yasb Bar
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
show_systray: true # Show YASB on the system tray.
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    animation:
      enabled: false
    blur_effect:
      enabled: false
    window_flags:
      always_on_top: false
      windows_app_bar: false
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    layouts:
      left:
        alignment: "left"
        stretch: true
      center:
        alignment: "center"
        stretch: true
      right:
        alignment: "right"
        stretch: true
    widgets:
      left: []
      center: [ "glazewm_workspaces" ]
      right: []
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "\u23fc Glazewm Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      animation: false
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 20
        hide_label: true
        hide_duplicates: true
        hide_floating: false
