# Ahmadinne's Yasb Bar
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: true
    animation:
      enabled: false
    blur_effect:
      enabled: false
    window_flags:
      always_on_top: false
      windows_app_bar: false
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    layouts:
      left:
        alignment: "left"
        stretch: true
      center:
        alignment: "center"
        stretch: true
      right:
        alignment: "right"
        stretch: true
    widgets:
      left: [ "microphone", "volume", "brightness", "systray" ]
      center: [ "glazewm_workspaces" ]
      right: [ "wifi", "bluetooth", "battery", "clock" ]
widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span><img src='$env:USERPROFILE/.config/yasb/svg/clock.svg' /></span> {%H:%M}"
      label_alt: "<span><img src='$env:USERPROFILE/.config/yasb/svg/clock.svg' /></span> {%A, %d %B %Y %H:%M}"
      timezones: []
      calendar: 
        blur: false
        round_corners: true
        alignment: "center"
        direction: "up"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "\u23fc Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      animation: false
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 20
        hide_label: true
        hide_duplicates: true
        hide_floating: false
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}"
      tooltip: true
      volume_icons:
        - "<img src='$env:USERPROFILE/.config/yasb/svg/volume-x.svg' />"
        - "<img src='$env:USERPROFILE/.config/yasb/svg/volume.svg' />"
        - "<img src='$env:USERPROFILE/.config/yasb/svg/volume-1.svg' />"
        - "<img src='$env:USERPROFILE/.config/yasb/svg/volume-1.svg' />"
        - "<img src='$env:USERPROFILE/.config/yasb/svg/volume-2.svg' />"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "toggle_volume_menu"
      audio_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "up"
        offset_top: 6
        offset_left: 0
        # show_apps: true
        # show_app_labels: true
        # show_app_icons: true
        # show_apps_expanded: true

  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}%"
      brightness_icons: [
        "<img src='$env:USERPROFILE/.config/yasb/svg/moon.svg' />",
        "<img src='$env:USERPROFILE/.config/yasb/svg/sun-dim.svg' />",
        "<img src='$env:USERPROFILE/.config/yasb/svg/sun-medium.svg' />",
        "<img src='$env:USERPROFILE/.config/yasb/svg/sun.svg' />",
      ]
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      icons:
        normal: "<img src='$env:USERPROFILE/.config/yasb/svg/mic.svg' />"
        muted: "<img src='$env:USERPROFILE/.config/yasb/svg/mic-off.svg' />"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_name}"
      label_alt: "<span>{wifi_icon}</span> {wifi_name}"
      get_exact_wifi_strength: false
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      wifi_icons: [
        "<img src='$env:USERPROFILE/.config/yasb/svg/wifi-off.svg' />",
        "<img src='$env:USERPROFILE/.config/yasb/svg/wifi-zero.svg' />",
        "<img src='$env:USERPROFILE/.config/yasb/svg/wifi-low.svg' />",
        "<img src='$env:USERPROFILE/.config/yasb/svg/wifi-high.svg' />",
        "<img src='$env:USERPROFILE/.config/yasb/svg/wifi.svg' />",
      ]
      menu_config:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "up"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: [ 
          "<img src='$env:USERPROFILE/.config/yasb/svg/lock-keyhole.svg' />",
          "<img src='$env:USERPROFILE/.config/yasb/svg/lock-keyhole.svg' />",
          "<img src='$env:USERPROFILE/.config/yasb/svg/lock-keyhole.svg' />",
          "<img src='$env:USERPROFILE/.config/yasb/svg/lock-keyhole.svg' />"
        ]
        wifi_icons_unsecured: [
          "<img src='$env:USERPROFILE/.config/yasb/svg/lock-keyhole-open.svg' />",
          "<img src='$env:USERPROFILE/.config/yasb/svg/lock-keyhole-open.svg' />",
          "<img src='$env:USERPROFILE/.config/yasb/svg/lock-keyhole-open.svg' />",
          "<img src='$env:USERPROFILE/.config/yasb/svg/lock-keyhole-open.svg' />"
        ]
  battery:
    type: "yasb.battery.BatteryWidget"
    options: 
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}%"
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: False
      status_thresholds:
        critical: 20
        low: 40
        medium: 60
        high: 85
        full: 100
      status_icons:
        icon_charging: "<img src='$env:USERPROFILE/.config/yasb/svg/battery-charging' />"
        icon_critical: "<img src='$env:USERPROFILE/.config/yasb/svg/battery-warning' />"
        icon_low: "<img src='$env:USERPROFILE/.config/yasb/svg/battery' />"
        icon_medium: "<img src='$env:USERPROFILE/.config/yasb/svg/battery-low' />"
        icon_high: "<img src='$env:USERPROFILE/.config/yasb/svg/battery-medium' />"
        icon_full: "<img src='$env:USERPROFILE/.config/yasb/svg/battery-full' />"
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span> {device_name}"
      label_alt: "<span>{icon}</span> {device_count} Devices"
      label_no_device: "Nothing"
      label_device_separator: ", "
      max_length: 10
      max_length_ellipsis: "..."
      icons:
        bluetooth_on: "<img src='$env:USERPROFILE/.config/yasb/svg/bluetooth' />"
        bluetooth_off: "<img src='$env:USERPROFILE/.config/yasb/svg/bluetooth-off' />"
        bluetooth_connected: "<img src='$env:USERPROFILE/.config/yasb/svg/bluetooth-connected' />"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: " ST"
      label_expanded: " ST"
      label_position: "left"
      icon_size: 16
      pin_click_modifier: "ctrl"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
